repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files

-   repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
    -   id: black

-   repo: https://github.com/pycqa/pylint
    rev: v3.0.0a6
    hooks:
    -   id: pylint
        args:
        - --max-line-length=120
        - --ignore-imports=yes
        - -d duplicate-code
        - --disable=import-error

- repo: https://github.com/thibaudcolas/curlylint
  rev: "" # select a tag / sha to point at
  hooks:
    - id: curlylint

-   repo: https://github.com/hadolint/hadolint
    rev: v2.10.0
    hooks:
        - id: hadolint
