version: '3'

services:
  app:
    build: .
    environment:
      - APP_ENV=dev
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app/src
      - ./frontend/public/build/:/app/frontend/public/build/
    depends_on:
      - node
    networks:
      - dev-net
  node:
    image: node:current-alpine
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=development
      - API_BASE_URL=localhost:8080
    volumes:
      - ./frontend:/home/node/app
    command: "npm run dev"

networks:
  dev-net:
