# Generated by Django 4.2.7 on 2023-12-18 23:05

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Mails",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("mail_text", models.TextField()),
                ("classifier", models.TextField()),
            ],
        ),
    ]
